version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
- gradlew.bat assemble --info --no-daemon

test_script:
- gradlew.bat check --info --no-daemon

cache:
- C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  fast_finish: true

artifacts:
- path: 'game\build\distributions\game-0.0.1.zip'
  name: Apollo Server Distribution
